server:
  port: 8072

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.99.234.82:8061/eureka/
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: systems.cubid.productservice