apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  labels:
    app: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: cubepixels/cubidshop-product-service
          ports:
            - containerPort: 8072

---
apiVersion: v1
kind: Service
metadata:
  name: product
  labels:
    app: product
    spring-boot: "true"
spec:
  type: ClusterIP
  clusterIP: 10.96.163.90
  ports:
    - port: 8072
      protocol: TCP
  selector:
    app: product