apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: cubepixels/cubidshop-user-service
          ports:
            - containerPort: 8071

---
apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    app: user
    spring-boot: "true"
spec:
  type: ClusterIP
  clusterIP: 10.100.20.109
  ports:
    - port: 8071
      protocol: TCP
  selector:
    app: user